### ISSUE TITLE
Concurrent call in SetPayment

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/MarketplaceCore#220]
On the live system there are alot of duplicated payment entries in the database with the same extinvoiceid.

This leads to some errors when the core is trying to update the status of a payment:

`vPaymentID := (select paymentid from payment where ExtInvoiceID = vExtInvoiceID);` returns more than 1 row

```
message=ERROR: more than one row returned by a subquery used as an expression 21000 at SetPayment, stack=error: ERROR: more than one row returned by a subquery used as an expression 21000 at SetPayment
2018-09-11T13:33:47.438079765Z     at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:539:11)
2018-09-11T13:33:47.438475252Z     at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:366:17)
2018-09-11T13:33:47.438698968Z     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:105:22)
2018-09-11T13:33:47.439025298Z     at emitOne (events.js:96:13)
2018-09-11T13:33:47.439250282Z     at Socket.emit (events.js:188:7)
2018-09-11T13:33:47.439490271Z     at readableAddChunk (_stream_readable.js:176:18)
2018-09-11T13:33:47.439737763Z     at Socket.Readable.push (_stream_readable.js:134:10)
2018-09-11T13:33:47.440053195Z     at TCP.onread (net.js:559:20), name=error, length=266, severity=ERROR, code=P0001, detail=undefined, hint=undefined, position=undefined, internalPosition=undefined, internalQuery=undefined, where=PL/pgSQL function setpayment(uuid,character varying,character varying,integer,uuid,uuid,text[]) line 116 at RAISE, schema=undefined, table=undefined, column=undefined, dataType=undefined, constraint=undefined, file=pl_exec.c, line=3165, routine=exec_stmt_raise
```

**Comment by MBeuttler** [comment]
4e9da347f3cc0eb67c89cb8d14afa66bfda8e760
